--

--UPDATE TABLE Address(id INTEGER PRIMARY KEY,userId INTEGER,address VARCHAR(300),FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)

--INSERT INTO User(name)
--VALUES ("Nagu")

--DELETE FROM User WHERE name = "gopi"

--SELECT *
--FROM Address

---UPDATE TABLE Address(id INTEGER PRIMARY KEY,userId INTEGER,address VARCHAR(300),FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE)
